#!/bin/bash
#SBATCH -J RANSR400
#SBATCH -o logfile 
#SBATCH -e errfile
#SBATCH -p gh
#SBATCH -N 8
#SBATCH -n 8
#SBATCH --ntasks-per-node 1
#SBATCH -t 8:00:00

module purge
module reset

module load nvidia/26.1 
module load cuda/13.1
module list

export NEKRS_HOME=$HOME/.local/nekrs-next
export PATH=$NEKRS_HOME/bin:$PATH

#rm -rf .cache
./config.sh

#ibrun nekrs --setup NACA.par
